### ISSUE TITLE
AttributeError: The following properties are unrecognized for PreferredPronoun: pronounId, pronounName

### ISSUE THREAD

**Issue by ssweetin** [partiallyderived/everyaction-client#2]
The `people.find` method gives an error when there is a `preferredPronoun` defined

> AttributeError: The following properties are unrecognized for PreferredPronoun: pronounId, pronounName

I don't know if it's related but I also see that the `preferredPronouns` property on [People](https://docs.everyaction.com/reference/people) and Reported Demographics [/pronouns](https://docs.everyaction.com/reference/pronouns) endpoints have been deprecated and replaced with `pronouns`. Ref: https://docs.everyaction.com/changelog/deprecated-preferredpronouns

This is the response that causes the AttributeError:

```
{
    ...
    
    "preferredPronoun": {
        "preferredPronounId": 3,
        "preferredPronounName": "They/Them/Theirs",
        "pronounId": 3,
        "pronounName": "They/Them/Theirs"
    },
    "pronouns": {
        "preferredPronounId": 3,
        "preferredPronounName": "They/Them/Theirs",
        "pronounId": 3,
        "pronounName": "They/Them/Theirs"
    }
    
}
```

**Comment by partiallyderived** [comment]
Fixed by latest commit, thanks by bringing this to my attention!
