### ISSUE TITLE
AttributeError: The following property is unrecognized for Person: isDeceased

### ISSUE THREAD

**Issue by ssweetin** [partiallyderived/everyaction-client#3]
As of a short time ago the `people.lookup` method gives an error for any contact.

> AttributeError: The following property is unrecognized for Person: isDeceased

The field is a boolean.

And thank you for fixing the last issue so quickly!

**Comment by partiallyderived** [comment]
No problem :). This issue is fixed in version 0.2.15, soon I will modify the code so that undocumented fields in responses print warnings instead of raising exceptions so new fields won't break the code anymore.
